### ISSUE TITLE
The mcohome App doesn't install pm 2.5

### ISSUE THREAD

**Issue by Don-new** [TedTolboom/com.mcohome#39] opened 2020-05-31 18:34 UTC
I try to connect my new mcohome pm 2.5 - wd with homey, but it will only install a universal z-wave device because no app knows what device it should be. Of course the mcohome App is already installed. Anybody the same issue and purhaps an idea what i do wrong? Thanks a lot!

**Comment by TedTolboom** [comment] 2020-05-31 19:02
Likely MCOhome released a new version with updated ID’s...
Can you share a screenshot of the advanced settings showing the product ID, productType ID?

**Comment by Don-new** [comment] 2020-05-31 19:42
Wow, thanks a lot for your fast answering! Amazing! Wehre i can support you with a Donation? PayPal? Attached i send you the actual informations. 
![20200531_213832](https://user-images.githubusercontent.com/61498513/83361250-a86f4b80-a387-11ea-8b18-5cf24bfaff1b.jpg)

**Comment by TedTolboom** [comment] 2020-06-01 14:30
It should be possible to include the PM2.5 sensor with the 1.3.5 version of the app; just uploaded to the app store.

While waiting for the approval, you can already install this update through below link:
https://homey.app/a/com.mcohome/test/

At the bottom, with the app details, there is a link to donate / contribute to the support of this app.

I'll close this issue for now, if unresolved or the sensor does not function properly, please create a new issue, ok?

Kind regards,

Ted

**Closed by TedTolboom** 2020-06-01 14:30 UTC

**Comment by Don-new** [comment] 2020-06-01 18:41
It works perfect! Thanks a lot for your fast help!

**Comment by TedTolboom** [comment] 2020-06-01 19:55
Thanks for reporting the issue and providing the feedback that the issue is resolved!
